version: "3"
services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    networks:
      - worktime2_default
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: WORKTIME2
    ports:
      - "5432:5432"
    networks:
      - worktime2_default
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - worktime2_default
volumes:
  postgres_data:
networks:
  worktime2_default:
    driver: bridge
